### ISSUE TITLE
Westerbork data not available

### ISSUE THREAD

**Issue by SETIADEEPANSHU** [SPINLab/westerbork-viewer#1]
Hi,

I really liked the concept you had built and would like to test it. I am able to set up the demo using docker but it does not show anything since I don't have the dataset to place in the pointclouds folder. Can you please share the data and the steps of converting point cloud to that format, I suspect you might be using Potreeconverter for the same.  

Current Output: Blank canvas with clouds and no point clouds in all the scenes

PS: I tried placing many datasets from pointclouds folder from Potree repo (https://github.com/potree/potree/tree/develop/pointclouds) to this repo respective folders.

**Comment by chrislcs** [comment]
Sorry for the late reply. I had not noticed this.

This project is not meant to be used by others. You can do with the code what you want (as per license), but I wont provide any support and the data used is private. Sorry.
